### ISSUE TITLE
General exception is shown for errors when redeeming vouchers

### ISSUE THREAD

**Issue by tecnomada** [cyclosproject/cyclos4-ui#132]
Add support for redeem voucher exceptions.
This should have been done in issue #44

**Comment by agonzalezcy** [comment]
UpperCreditLimitReachedException is not informed when redeem a voucher


When a user try to redeem a voucher by an amount which cause that the UpperCreditLimit would be reached, the user get a message 
"There was an unexpected error .....", we should inform to redeemer than him can not redeem the voucher because his account Upper credit limis would be reached. 

Analyze the same problem when the payment voucher destination is different the logged user (The vouchertype has PaymentDestination=FixedUser and the selected user is not the loggedin user)
