### ISSUE TITLE
How to host the new ui out side of cyclos just like the v1 or v2

### ISSUE THREAD

**Issue by anantanandgupta** [cyclosproject/cyclos4-ui#417]
I need to be able to host  the new cyclos ui separately from cyclos admin. I have tried many things but it seems that the new ui is tigtly coupled with the cyclos and in some manner designed to be running from within the cyclos installation. Is there any guide or instructions which can explain what to do to achive this. Ui should be independently configurable and it should not depend on the cyclos to be configured. 

The main trouble point of this being part of the cyclos is continuous enhancement and customizations required on the ui side for the customer facing site and I don't want to kepp on deploying cyclos on a server. 

As this is an angular application and can server statically the independent deployment can be must faster without asking for the downtime or with minimal impact on the availability of the service.

Production url is always pointed to /api of the current domain and even if we hardcode the api url, it takes the user to the cyclos server as the cyclos is still configured to classic ui. 

How to make this happen without telling cyclos to be also shoing new ui.

**Comment by luisfpg** [comment]
Hi @anantanandgupta. Really, from 4.14 onwards, the new frontend is designed to run within Cyclos.
If you follow the instructions to [update the UI served by Cyclos](https://github.com/cyclosproject/cyclos4-ui#updating-the-frontend-version-served-by-cyclos-with-your-customized-one), you'll notice that only static resources + a JSP file are changed (from Cyclos POV). And this doesn't need a server re-reploy.
And, if users anyhow use the new frontend, would it be a problem to configure Cyclos to use the new frontend for them?

**Comment by anantanandgupta** [comment]
Hi @luisfpg, the problem lies in the past. We have our product designed / implemented in such as way that the members never directly reach to the cyclos server / domain. They only interact with this UI which is hosted separately on different domain which consumes the APIs exposed by cyclos server.

cyclos server can be only accessed via an internal VPN by admins only. this design was done as the UI was externally available and facilitated by cyclos. Now if Cyclos comes back and says that this UI can't be hosted outside anymore, and at the same time the old UI version will become outdated very soon as it is no more enhanced our bank will have to be destroyed.

**Comment by luisfpg** [comment]
Hi @anantanandgupta . I've updated the README to include instructions on how to host the frontend separatedly from Cyclos. See https://github.com/cyclosproject/cyclos4-ui#hosting-the-frontend-separatedly-from-cyclos

The only actual change you will need is to configure in Cyclos that users should use the new frontend, without allowing them to switch. As you need anyhow to configure Cyclos to use the link generation script, you should use the same configuration(s) to also define the frontend.

**Comment by anantanandgupta** [comment]
Quite some work to done but will give it a try soon and get back to you. Thanks for the guide.

**Comment by fvbaag** [comment]
not working :(

here is the setup using docker containers (domains are hosted by nginx reverse proxy). So

Containers:
```
- frontend (nginx hosting frontend static site)
- backend (cyclos container  @ 8080 + cyclos db container)
- nginx (reverse proxy configuration)
  - forwards the requests on https://localprod.domain.com to frontend container
  - forwards the requests on https://localprod.backend.domain.com to backend container while terminating the ssl
```

## configurations
```
Global Config
Main URL: https://localprod.backend.domain.com
- Network Config (inherited from Global Config)
  Main URL: https://localprod.backend.domain.com/Online_Banking
  - Member Config (inherited from Network Config)
    this config is applied to the group set containing the member groups and the new ui is enabled with the guide supplied in the readme.md
```

### use case 1: access the backend directly by accessing https://localprod.backend.domain.com
we can access the public content but after login using the member account the ui is all distorted. see the screenshot below:
![image](https://user-images.githubusercontent.com/84617998/119225286-7dde4b80-bb20-11eb-8874-1078eeeeb22a.png)

this is because cyclos is not considering the main url protocol to generated the urls for the styles and images, but it is converting the url to http://localprod.backend.domain.com/** and browser is blocking the mixed content. (http and https)

**Please note** that this is only happening when the new ui is rendered. But if the classic ui is rendered the above issue is not more there. The classic ui is rendering properly (except shortcut url and /api for api documentation). 

### use case 2: access the frontend hosted outside cyclos
this redirects the ui to /classic as the call to the api https://localprod.domain.com/api/frontend/data?screenSize=desktop returns the classic as frontend. 

this doesn't end here, it goes into an infinite redirect loop some how.

I will be raising a technical support ticket also regarding this issue, but this is not as easy as it seems to be to setup the new UI externally.

**Comment by luisfpg** [comment]
Sorry @anantanandgupta, but we really have some issues that makes it very hard to deploy a separated frontend.
When I updated the README I didn't take into account that the backend cannot be accessed.
We will work on this, and will likely have it working on 4.14.10. We need to figure some issues... You'll be informed when we have progress on this.
