### ISSUE TITLE
Please add "Last transaction" filter on the 'User balances overview' page

### ISSUE THREAD

**Issue by rhornig** [cyclosproject/cyclos4-ui#424]
We are regularly reaching out for users who were not active in the last year or so. For this we used a filter where you were able to filter for the last transaction date of the user (either incoming or outgoing). (Filtering for "Last login date" is not appropriate, because we consider users active also when they receive a transaction.) This was possible on older versions, but the filter disappeared in recent versions (both the classic and the new UI.)

Would you consider adding back a filter for "Last transaction" on the 'User balances overview' page?
Thanks a lot for your great work.

**Comment by luisfpg** [comment]
Even though we understand it was useful, we had major performance problems because of that filter.
Cyclos is very complex, and used by some very large systems.
The search in Cyclos can be either done in the database or in Elasticsearch. In both we had problems because of that filter:

- On database, we'd need to fetch, per user, the last transaction date, which made the query very slow for middle databases already;
- On Elasticsearch, the time to index each user was very high, because we'd need to fetch, per account, the last transaction date. Keep in mind that there are systems where users have multiple accounts. So, the user indexing was very, very slow.

In the end, we decided the only real solution was to remove the feature. And, because of the mentioned issues, it is not going back.
Customers really needing this can query the database directly.
